const HEADER_HEIGHT_NUMBER = 10;
const HEADER_HEIGHT = `${HEADER_HEIGHT_NUMBER}dvh`;
const FOOTER_HEIGHT_NUMBER = 0;
const FOOTER_HEIGHT = `${FOOTER_HEIGHT_NUMBER}dvh`;
const BODY_HEIGHT = `${100 - HEADER_HEIGHT_NUMBER - FOOTER_HEIGHT_NUMBER}dvh`;

export { HEADER_HEIGHT, FOOTER_HEIGHT, BODY_HEIGHT };